const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine');
function simple(now=780){const s=E.createState();s.now=now;s.lastPoll=now;s.tasks=[];return s;}
const task=(id,estimate,deadline=1080,more={})=>({id,title:id,estimate,deadline,must:true,spent:0,status:'todo',revision:0,...more});
test('午休和重叠会议只扣一次，周末不可用',()=>{const s=simple(540);s.meetings.push({start:930,end:990});assert.equal(E.available(s,540,1080),390);assert.equal(E.available(s,2*1440,4*1440),0);});
test('两个任务共用时间，不为每个任务重复分配可用工时',()=>{const s=simple();s.tasks=[task('a',180),task('b',60)];const p=E.plan(s);assert.equal(p.capacity,240);assert.equal(p.required,240);assert.equal(p.gap,0);assert.equal(p.rows[1].end,1080);});
test('分别检查中途 deadline：全天排得下也可能延误',()=>{const s=simple();s.tasks=[task('a',150,900)];const p=E.plan(s);assert.equal(p.gap,0);assert.equal(p.late.length,1);assert.equal(p.rows[0].end,990);});
test('提前30分钟提醒，重复检查不会重复触发；快进不漏边界',()=>{const s=simple(700);s.tasks=[task('a',180),task('b',60)];const p=E.plan(s);assert.equal(p.rows[0].latestStart,780);assert.equal(p.rows[0].remindAt,750);assert.equal(E.evaluate(s).length,0);const alerts=E.advance(s,60);assert.equal(alerts.filter(a=>a.type==='start').length,1);assert.equal(E.evaluate(s).length,0);});
test('切换任务自动暂停，跨午休和会议仅记录可用工作时间',()=>{const s=simple(690);s.tasks=[task('a',300),task('b',60)];E.apply(s,{type:'start',id:'a'});E.advance(s,120);assert.equal(s.tasks[0].spent,60);E.apply(s,{type:'start',id:'b'});assert.equal(s.tasks[0].status,'todo');assert.equal(s.tasks[1].status,'active');E.advance(s,30);assert.equal(s.tasks[0].spent,60);assert.equal(s.tasks[1].spent,30);});
test('超出预估后询问剩余工时，不自动完成',()=>{const s=simple();s.tasks=[task('a',30)];E.apply(s,{type:'start',id:'a'});const a=E.advance(s,35);assert.equal(s.tasks[0].status,'active');assert.equal(a.filter(x=>x.type==='estimate').length,1);E.apply(s,{type:'remaining',id:'a',minutes:60});assert.equal(E.remaining(s.tasks[0]),60);assert.equal(s.tasks[0].spent,35);});
test('等待任务保留工作量和风险，但不推荐执行',()=>{const s=simple();s.tasks=[task('a',300,1080,{status:'waiting'}),task('b',30)];const p=E.plan(s);assert.equal(p.required,330);assert.equal(p.gap,90);assert.equal(p.recommendation,'b');assert.equal(p.rows[0].conditional,true);});
test('同一轮多消息合并一条，未经确认不创建任务',()=>{const s=E.createState(),n=s.tasks.length;E.queueMessage(s,'new');E.queueMessage(s,'review');assert.equal(s.tasks.length,n);E.advance(s,29);assert.equal(s.messages[0].status,'queued');const alerts=E.advance(s,1);assert.equal(alerts.filter(a=>a.type==='messages').length,1);assert.equal(s.tasks.length,n);const m=s.messages.find(m=>m.scenario==='new');E.confirm(s,m.id);assert.equal(s.tasks.length,n+1);assert.throws(()=>E.confirm(s,m.id));});
test('deadline变更预览不修改原始状态，确认后才生效',()=>{const s=E.createState();const m=E.queueMessage(s,'deadline');E.poll(s);const before=E.clone(s);E.preview(s,m.id);assert.deepEqual(s,before);E.confirm(s,m.id);assert.equal(s.tasks[0].deadline,960);});
test('资料到达使等待任务可恢复；未定deadline不捏造期限',()=>{const s=E.createState();E.queueMessage(s,'material');const unknown=E.queueMessage(s,'unknown');E.poll(s);assert.equal(s.tasks.find(t=>t.id==='t3').status,'todo');E.confirm(s,unknown.id);assert.equal(E.plan(s).unknown,1);const t=s.tasks.at(-1);assert.throws(()=>E.apply(s,{type:'start',id:t.id}));});
test('接受插单后暴露缺口，忽略变更不改承诺',()=>{const s=simple();s.tasks=[task('t1',180),task('b',60)];const m=E.queueMessage(s,'new');E.poll(s);E.confirm(s,m.id);assert.equal(E.plan(s).gap,60);const d=E.queueMessage(s,'deadline');E.poll(s);E.apply(s,{type:'dismiss-message',id:d.id});assert.equal(s.tasks[0].deadline,1080);});
test('未确认的输入不会允许NaN或负工时',()=>{const s=E.createState();assert.throws(()=>E.apply(s,{type:'edit',id:'t1',values:{estimate:-10}}));assert.throws(()=>E.apply(s,{type:'meeting',start:NaN,end:900}));assert.throws(()=>E.advance(s,-1));});
test('手动排序只改变同优先级内顺序，完成后释放工时',()=>{const s=simple();s.tasks=[task('a',60,900),task('b',60,1080),task('c',60,850,{must:false})];E.apply(s,{type:'reorder',id:'b',direction:-1});assert.deepEqual(E.ordered(s).map(t=>t.id),['b','a','c']);E.apply(s,{type:'complete',id:'a'});assert.equal(E.plan(s).required,120);});
test('主动切换到低优先级工作，预测必须反映当前执行选择',()=>{const s=simple();s.meetings=[];s.tasks=[task('a',60,840),task('b',120,1080)];assert.equal(E.plan(s).late.length,0);E.apply(s,{type:'start',id:'b'});const p=E.plan(s);assert.equal(p.rows[0].id,'b');assert.equal(p.late[0].id,'a');});
